### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by macnick**
Please review our code. 

The project link will work after we merge with the master.

### CODE REVIEW

**Comment by samgaco** [comment]
Hi @macnick  and @dannyclever :wave:

The project looks like is heading in the right direction so far :v: and I really like how descriptive is the readme file, anyways, there are some things to improve and sections to add:

* You should at least add images (when they appear in the original website) in the top left corner of the articles. The animation is not needed, but an embedded image should be there (it doesn't need to be the same image).
article

* You didn't implement some sections and different design articles such as:

1. This red articles here:
sec

2. This other article area at the end:
sec2

3. This section right before the footer:
sec3

4. And other sections that you can see around that are not implemented, etc. In general, you should think of this project as if it were an outline of the original, you can _draw it free-hand_, but it should feel like it does have the structure of the original.

* The footer should be centered, and again preserve the structure of the original, even if it doesn't hold exactly the same content. You can position the content of the lists in the footer using float or flex.
footer

* Bear in mind the following semantic structure; All content should be wrapped within` <main>` tags (you only have a small portion of the content currently inside the `<main>` tags), every child of main should be enclosed within a `<section>` tag and every child of section within an `<article>` tag.

Please :pray: , work on all these changes and additions and submit back for another code review when you are done. Working on this will surely make you grow as developers. I hope you keep the good work you've been doing until now. Regards and happy coding! :muscle:

**Comment by macnick** [comment]
Thank you for your review and your kind words.

According to the guidelines and I quote "the purpose is to create a grayscale heat map of the website that indicates which elements have the greatest weight in the visual hierarchy." Not to recreate the whole site. Nevertheless we liked your suggestions and tried to implement them as closely to original as possible.
1. We put the red articles in the corresponding places
2. We added the article area at the end
3. Added the newsletter section near the footer
4. Also added the rest of the sections that were missing
5. We followed your advice and recreated the footer using ul and li and styled it appropriately.

Also we took care of the semantics of the page and placed the main and sections better. 

Please review our code again.

**Comment by samgaco** [comment]
Hi @macnick  and @dannyclever :hand: 

You are right, but creating a heat map of the website would have included more outlined sections of the original than it had before, so it could feel like it is representing the design of the original. I felt the previous model was lacking many parts of the original design.

These new changes you implemented look great anyways, I can really tell you put a lot of hard work into it, everything looks perfect now. **Before approving the project, I'd like to address the following points;**

* Visualizing the index you can see that there is extra space at the right side (the horizontal bar shouldn't be making an appearance)
* There is more commits by @macnick than @dannyclever. I'd like to remind you that the commits should be made in turns, it's not strict, but certain flow should be seen. Microverse suggests taking turns of around 40 minutes each.
* Correct the errors given by https://validator.w3.org

Your project is looking superb now. So please :pray: just address this 3 points and submit back for a code review. Regards and thanks for your understanding! :muscle:

**Comment by macnick** [comment]
Hello @samgaco,
Thank you for the fast review and encouraging words.
* We fixed the extra space at the right and the horizontal bar does not appear any more.
* We try to work using the flow. 
* We corrected the errors given by the validator. 

Thanks.

**Comment by Ispirett** [comment]
Excellent work on your changes folks :1st_place_medal:  You can merge this project
and fill out a completion form. 
- [ ] **Bonus tip** you should include the h1 - h6 always in article and section. You can hide it if you don't want it to show.

Also important note for feature HTML projects use a feature branch instead of development you can give that branch descriptive name that describes the feature you are implementing.

**Comment by macnick** [comment]
Hello @Ispirett 
Thank you so much for your fast review and kind words. 
We will make use of your tips in out next project. 
Thank you.

**Pull request merged**
